# Version-specific properties for Minecraft 26.1.x
minecraft_version=26.1
yarn_mappings=
loader_version=0.19.2
fabric_version=0.145.1+26.1
fabric_kotlin_version=1.13.11+kotlin.2.3.21
modmenu_version=18.0.0-beta.1
paper_version=26.1.2.build.63-stable
paperweight_version=2.0.0-SNAPSHOT
org.gradle.parallel=true
loom_version=1.16-SNAPSHOT
kotlin_version=2.3.10
mod_version=0.2.7
maven_group=codes.castled.axion
archives_base_name=axion
org.gradle.jvmargs=-Xmx3G
