# Version-specific properties for Minecraft 26.1.x
minecraft_version=1.21.7
yarn_mappings=1.21.7+build.1
loader_version=0.16.13
fabric_version=0.129.0+1.21.7
fabric_kotlin_version=1.13.0+kotlin.2.1.0
modmenu_version=15.0.2
paper_version=1.21.7-R0.1-SNAPSHOT
paperweight_version=2.0.0-SNAPSHOT
org.gradle.parallel=true
loom_version=1.15.4
kotlin_version=2.3.10
mod_version=0.2.11
maven_group=codes.castled.axion
archives_base_name=axion
org.gradle.jvmargs=-Xmx3G
