package axion.client.input

import axion.client.symmetry.SymmetryController
import axion.client.tool.PlacementToolController
import net.minecraft.client.MinecraftClient

object AxionShortcutPreemption {
    /**
     * Drains only the vanilla offhand click generated by an active Axion Ctrl+flip
     * shortcut. This runs at the head of Minecraft's keybind processing, before the
     * vanilla SWAP_ITEM_WITH_OFFHAND packet can be sent.
     */
    fun suppressConflictingOffhandSwap(client: MinecraftClient) {
        val mirrorKeyDown = KeyBindingHandler.isBoundKeyDown(AxionKeybindings.symmetryToggleMirror)
        val shouldSuppress = AxionShortcutPreemptionPolicy.shouldSuppressOffhandSwap(
            controlDown = AxionModifierKeys.isControlDown(client),
            mirrorKeyDown = mirrorKeyDown,
            canFlipPreview = PlacementToolController.canMirrorPreview(),
            canToggleMirror = SymmetryController.canToggleMirrorFromHotkey(),
        )
        if (!shouldSuppress) {
            return
        }

        while (client.options.swapHandsKey.wasPressed()) {
            // Consume all queued presses for this physical key event before vanilla.
        }
    }
}
