import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id('multiloader-common')
    id('net.neoforged.moddev')
}
apply plugin: 'org.jetbrains.kotlin.jvm'

neoForge {
    neoFormVersion = neo_form_version
}

neoForge.addModdingDependenciesTo(sourceSets.main)

configurations {
    neoFormClasses
}

dependencies {
    neoFormClasses(files("build/moddev/artifacts/vanilla-${neo_form_version}.jar"))
    implementation project(':protocol')
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    testImplementation "org.jetbrains.kotlin:kotlin-test:${kotlin_version}"
}

configurations.compileClasspath {
    extendsFrom(configurations.neoFormClasses)
}
configurations.runtimeClasspath {
    extendsFrom(configurations.neoFormClasses)
}

tasks.named('compileJava') {
    dependsOn 'createMinecraftArtifacts'
}
tasks.named('compileKotlin') {
    dependsOn 'createMinecraftArtifacts'
}

tasks.named('test') {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(java_version as int)
    compilerOptions {
        jvmTarget.set(JvmTarget.fromTarget(java_version as String))
        freeCompilerArgs.add('-jvm-default=no-compatibility')
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release.set(java_version as int)
}
