modLoader="javafml"
loaderVersion="[4,)"
license="${license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
description="${description}"
authors="${mod_author}"
logoFile="assets/axion/icon.png"

[[mixins]]
config="axion.client.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
